### ISSUE TITLE
Duplicate tags in SageMaker dev notebook (Service Catalog)

### ISSUE THREAD

**Issue by WPrintz** [aws-samples/secure-data-science-quickstart#2]
In Lab 2: Deploy a Project environment, when the Service Catalog product "example-project SageMaker dev notebook" is added to the portfolio, the Service Catalog product has duplicate tags in the "Launch options" for tags "EnvironmentType" and "ProjectName".  The "Launch options" duplicate tags appear when viewed through the end-user Products console page (not seen in the Service Catalog Administration console view).

With the beta version of the Service Catalog console, the  "example-project SageMaker dev notebook" product will fail to launch in Lab 3 because of duplicate tags.  The duplicate tags do not seem to be blocking when the product is launched through the old console.

**Comment by WPrintz** [comment]
[Edited to specify correct product name]

**Comment by jpbarto** [comment]
closed b1c0513a4d4852373a905c5cb147f310fed3291a
